// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JgT6Sxq-YS6gxW4esU5wEcSURJQx0Bs',
    appId: '1:483945896413:web:84abc4f49a257dad1bfe34',
    messagingSenderId: '483945896413',
    projectId: 'myadd-295e5',
    authDomain: 'myadd-295e5.firebaseapp.com',
    storageBucket: 'myadd-295e5.firebasestorage.app',
    measurementId: 'G-GRTMP8WX2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5heIig4Bjs_5qX1SLsITt_xWGktURsA4',
    appId: '1:483945896413:android:49e880c4ca58c5931bfe34',
    messagingSenderId: '483945896413',
    projectId: 'myadd-295e5',
    storageBucket: 'myadd-295e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISV1YIMrGnfJ2wa1guAvtaKaEILYIk5Q',
    appId: '1:483945896413:ios:88abde97e12cbcd21bfe34',
    messagingSenderId: '483945896413',
    projectId: 'myadd-295e5',
    storageBucket: 'myadd-295e5.firebasestorage.app',
    iosBundleId: 'com.example.myadds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCISV1YIMrGnfJ2wa1guAvtaKaEILYIk5Q',
    appId: '1:483945896413:ios:88abde97e12cbcd21bfe34',
    messagingSenderId: '483945896413',
    projectId: 'myadd-295e5',
    storageBucket: 'myadd-295e5.firebasestorage.app',
    iosBundleId: 'com.example.myadds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4JgT6Sxq-YS6gxW4esU5wEcSURJQx0Bs',
    appId: '1:483945896413:web:9a3b84cf8433e1881bfe34',
    messagingSenderId: '483945896413',
    projectId: 'myadd-295e5',
    authDomain: 'myadd-295e5.firebaseapp.com',
    storageBucket: 'myadd-295e5.firebasestorage.app',
    measurementId: 'G-ZCX5XSGWD5',
  );
}
